### ISSUE TITLE
Create regular user from CLI (command)

### ISSUE THREAD

**Issue by bash-stack** [repman-io/repman#159]
#### Circumstances:
* custom gitlab
* disabled user registration to prevent spam

→ currently creating new users from cli as admin and dropping their rights  , unsuitable for serious deployments

## suggestions: 
- [x] add `bin/console  repman:create:user` command to add regular user
- [ ] add web-gui option "`only allow account creation from` gitlab/github/providerXYZ"  when there are ONLY gitlab/github/providerXYZ users

**Comment by akondas** [comment]
First looks ok. Second option need more detailed description, I think it will be related with (#58). Generally, such integration will open a window for even more possibilities, so it will definitely jump on our roadmap. Thanks for the feedback.

**Comment by bash-stack** [comment]
The second one should go like this:

frontend with only ONE auth button -> gitlab/github/bitbucket -> create user 

since there should be no public registration , only oauth'ies from  self hosted gitlab/younameit should be able to register

**Comment by nickygerritsen** [comment]
For the second part of this issue: the problem currently is that disabling registration disables both local and oauth registration.

Perhaps a new option, 'disable local authentication' would fix this? This would then disabling:
* Locally logging in with a username/password
* Locally registering
* Changing your password

I could create a PR for that if that sounds like a good idea? It is something we would like to have, since we use GitLab for all our authentication, so we don't want/need local users login all.

**Comment by akondas** [comment]
Sounds good, we can do separate options with this:
- [ ] User email/password registration
- [ ] User oath registration

**Comment by nickygerritsen** [comment]
Don’t we have oauth registration already because we only show oauth buttons for env vars you have set?

**Comment by akondas** [comment]
Yes and no. Env vars show and hide buttons for both registration and login, this is a different concept. This option in the administration allows you to directly enable / disable the registration process itself.

**Comment by nickygerritsen** [comment]
Ok but I was proposing also hiding *login* for email/password users. So a bit like the env var.
Then maybe split it like this:
* checkbox for oauth reg
* select for email/password with three options: allow login+reg, allow login but disable reg; fully disallow

We don’t have the select for oauth since we have the env var to do that.

Thoughts?

**Comment by akondas** [comment]
It sounds ok to me. @karniv00l?

**Comment by bash-stack** [comment]
(reminder: currently the oauth providers have to be defined , but empty , so 
`OAUTH_EXAMPLE-PLAFTORM_VALUETHINGY=` works , but not defining kills the system )

**Comment by karniv00l** [comment]
Looks good to me
