### ISSUE TITLE
Enterprise implemenation

### ISSUE THREAD

**Issue by luckyraul** [repman-io/repman#203]
Hi, thanks guys for a good app.

I am playing with your app and planning to implement it in our Development Flow. 

We have multiple teams, which should be fully isolated from each other, except a few shared packages. We also have a vendor, which has multiple private packages, which should be shared for everyone authenticated. 

Every developer has a personal OpenLDAP account, but we use OpenID Connect to authenticate (SSO).   
At the bottom there is my list of things  I need to have to launch in production., can do you have any plans to add such a feature? 

1. I can split teams as a different organizations in the current situation. Can a user be in multiple organization/teams?  We need this.
2. LDAP Users
3. OpenID Connect 
4. Sync vendor private repository
5. Disable LDAP Auth ( It can be useful to prevent using LDAP credentials through the web UI when an alternative such as OpenID Connect is preferred. This allows LDAP to be used for group sync, while also allowing your OpenID Connect identity provider to handle additional checks like custom 2FA. and protects from auth by deleted user.
7. Does it sync dev branches?
8. org.repo.repo.corp.xxx.xxx  - it is a very long domain name. Can we use folders per organisation? Can repo domain prefix be configured? 
7. Sync support of a hosted bitbucket?

**Comment by akondas** [comment]
1. It is already possible (with team members)
2. This has already been reported, you would have to specify exactly how it would look/work (#58)
3. This is very easy to implement, see other Oauth (for example, gitlab or gitub)
4. It is already possible.
5. You can partially do such things through the instance configuration, but further work will definitely be required.
6. Yes.
7. Moving to folders will not be possible because composer allows authorization on individual domains / subdomains. The folder alone is not enough to separate individual access tokens. If the domain name is too long for you, you can always set some proxy or alias in dns.
8. I haven't tested, but it should work.

If there are any questions I will gladly help.

**Comment by luckyraul** [comment]
Good news ! 

4. How ?  A Vendor Composer Repo.
8. Bitbucket Cloud + Hosted Bitbucket

**Comment by luckyraul** [comment]
There is actually one more feature we need. To store composer tag zips on S3/Swift.

**Comment by akondas** [comment]
In that case, I suggest opening a separate issue on each of these topics in which we could discuss the implementation. If something else is not clear then we can finish the discussion here.

**Comment by luckyraul** [comment]
@akondas

**Comment by akondas** [comment]
> How do add Vendor Composer Repo?

This is not possible at the moment. But I would like to specify here whether it is one package or if someone else shares their packages using (for example) Satis. 

> Can we use Bitbucket Cloud and Hosted Bitbucket together?

This is actually possible. Bitbucket Cloud is supported (you only need to add the oauth key for the standalone version). As for Hosted Bitbucket, you could add a repman instance public key (to your bitbucket server) and configure the network so that repman can connect to your bitbucket. Then adding and synchronizing repositories will be possible (by entering the repository url in repman url). I don't have a Hosted Bitbucket instance to test it, but if it works like Gitlab it should work :wink:

**Comment by akondas** [comment]
Hello @luckyraul, is there anything else to discuss here or can we close this issue for now?

**Comment by luckyraul** [comment]
We can close, however I have one last question: 
Do you have any plans to mix your app with satis? 
Mostly our needs are to grant personal access(oauth/oidc) base on team to restricted repos without touching them in bitbucket, and redistribute vendor private satis. 

I can help implement.

**Comment by akondas** [comment]
We don't have anything like this in the backlog, but contributions are welcome. How would the flow of such functionality look like and what exactly would this integration consist of?

**Comment by luckyraul** [comment]
1. Repman periodically dumps specific packages from every vendor's packagist via personal auth.json ( I assume to vendor named team in organization ). These packages are accessible to users, joined these vendor teams. Normal Satis flow.
2. From bitbucket cloud we add huge amount of projects grouping them by team. ( Normal Repman Flow )
2. Person, authenticated via OAUTH/OIDC, joins team(s) automaticly, via JSON/JWT field.  
Can use their personal token in local auth.json to download

**Comment by akondas** [comment]
Looks like a very specific case. We certainly do not have something like this in the backlog, but I can help with the implementation and review pull requests.

**Comment by akondas** [comment]
If you have any questions or concerns, please create a separate issue in this matter. Cheers :beers:
