### ISSUE TITLE
Members should only be able to see and manage their own tokens.

### ISSUE THREAD

**Issue by nauxliu** [repman-io/repman#279]
1. Organization members should only be able to manage tokens created by themself, not all tokens in the organization.
2. We should delete all token created by the member who leaves the Organization

 In this way, we don't have to reset all tokens when an employee leaves.

**Comment by nauxliu** [comment]
We are happy to make a PR if you approve of this proposal.

**Comment by akondas** [comment]
Hello @nauxliu 
It makes perfect sense. But we also have cases where we would like to share tokens (small organizations). We could choose its `scope` when creating tokens. For example `scope`:
- `private` - available and visible only to a given member
- `public`  - available and visible only to all members

This solution also provides backward compatibility, because unfortunately we are not saving the token creator at this point.
