### ISSUE TITLE
PostgreSQL exposure?

### ISSUE THREAD

**Issue by alexhorner** [repman-io/repman#409]
Hi there,

I noticed that after installing repman via docker, port 5432 is exposed publicly and exposes the PostgreSQL database to password authenticated access. Having a database exposed to the public facing internet is not a good idea, so I prompotly removed the port from the compose config, which has had no visible effect on the operation of repman.

Is there a reason this port is exposed?

**Comment by akondas** [comment]
Yes, you are right this port should not be exposed. We assumed that probably everyone covers their instance with proxy, load balancer or something similar, so somehow no one paid any attention to it. We are about to fix the default configuration, because this port is not needed for anything. Thank you for opening an issue on this.
