### ISSUE TITLE
repman behind corporate proxy

### ISSUE THREAD

**Issue by sporykhin** [repman-io/repman#431]
Looks like I need a way to pass HTTP_PROXY variable inside the app. Is there any chance to do this by configuration files?

```
16:26:04 ERROR     [console] Error thrown while running command "repman:security:update-db". Message: "The process "'git' 'clone' '--depth' '1' '--branch' 'master' 'https://github.com/FriendsOfPHP/security-advisories.git' '.'" exceeded the timeout of 60 seconds." ["exception" => Symfony\Component\Process\Exception\ProcessTimedOutException { …},"command" => "repman:security:update-db","message" => "The process "'git' 'clone' '--depth' '1' '--branch' 'master' 'https://github.com/FriendsOfPHP/security-advisories.git' '.'" exceeded the timeout of 60 seconds."]

In Process.php line 1213:

  The process "'git' 'clone' '--depth' '1' '--branch' 'master' 'https://githu
  b.com/FriendsOfPHP/security-advisories.git' '.'" exceeded the timeout of 60
   seconds.


repman:security:update-db
```

**Comment by sporykhin** [comment]
I`ve got the solution:
add http_proxy to environments variables inside containers 

maybe we can add some vars into .env.docker file?

**Comment by akondas** [comment]
`.env.docker` is a file where users make their own changes, you can type whatever you want there. From the project side, I do not see the need to add the HTTP_PROXY variable there, because we do not use it by default, and for each user this value will probably be different.

Of course I can be wrong so I am open to further discussion.

**Comment by sporykhin** [comment]
Ok
