### ISSUE TITLE
Multiple emails sent for vulnerabilities

### ISSUE THREAD

**Issue by binaryfire** [repman-io/repman#448]
Hi all

The vulnerabilities scan is a great feature, but shouldn't it only send email notifications once? At the moment emails about the same vulnerabilities are being sent every couple of days.

**Comment by akondas** [comment]
Messages with the scan result are sent each time such a scan is performed. Currently, when updating the vulnerability database, such a scan starts automatically, so you receive this message more than once. This should motivate you to fix the vulnerabilities.

You might be tempted to introduce an option that would allow you to "freeze" the scan for a given package. But in order to do this, more people would have to appear. I'm closing for the moment. If you have any further questions, comments or doubts, feel free to discuss.
