### ISSUE TITLE
Possible impact on composer funding

### ISSUE THREAD

**Issue by dcabrejas** [repman-io/repman#46]
If I understand this correctly, offering a similar service to private packagist for free will likely reduce the revenue of private packagist. By doing this, the fundings available to the composer project will go down. How does having this service free help support composer and packagist?

**Comment by akondas** [comment]
Thank you for pointing that out. We created Repman as a solution to our internal needs and decided to release it as open-source so that other developers can use it, too.

Composer is the cornerstone for every PHP and WordPress developer. We know it, we use it, and we love it. We already have a couple of ideas for optimizing Composer in CI/CD, too, with the team ready to actively participate in the development process. Look out for new pull requests in the upcoming weeks.

If you have any ideas developing new or improving existing features for Composer, make sure to link to the issues in this project. We’ll be happy to provide any assistance that we can.

**Comment by dcabrejas** [comment]
Hi @akondas 

Glad to hear that you guys plan to contribute to the project. I'm a PHP developer myself and also relay on that project and I hope they can continue to get funding and improve the project. I am sure it's not your intention to harm the project in any way and I hope that this project doesn't have a negative impact on Private Packagist and the Composer project in general. 
Could be worth reaching out to the Packagist team to discuss with them the impact that this might have on them if you wanted to do that 👍
