### ISSUE TITLE
Bitbucket: new tags are not synchronized

### ISSUE THREAD

**Issue by peter-bztrs** [repman-io/repman#490]
Using the Cloud version of Repman.io

Attached Bitbucket cloud to repman.io for use as private repository
Added repository to repman.io with one tag in it: 1.0.0

We've 'released' a new version with the tag 1.0.1.
In Bitbucket and in Git this tag is shown correctly.
Also the version number in composer.json is correct.

**Tried to following:**
- Synchronise the repository from out repman.io
- deleted the repository in repman.io and added the repository again.

The result for both is that only the 1.0.0 tag is visible.

**Comment by akondas** [comment]
Hi Peter, thanks for reporting.
Can you make the repository available so that I can reproduce the bug? Right now I have tested the Bitbucket integration and everything works fine.

![Screenshot from 2021-06-26 07-47-46](https://user-images.githubusercontent.com/8239917/123503394-076ac700-d653-11eb-8560-cf2eca6d6fea.png)

You can also check repository webhook history in Bibukcet: Repository -> Setting -> Webhooks -> Enable history:

![Screenshot from 2021-06-26 07-53-45](https://user-images.githubusercontent.com/8239917/123503528-c2936000-d653-11eb-9339-a8ed93709b84.png)

And finally, one question: does manual synchronization help and the mentioned version appears in the repman?

**Comment by peter-bztrs** [comment]
> Can you make the repository available so that I can reproduce the bug? Right now I have tested the Bitbucket integration and everything works fine.

https://bitbucket.org/sition_nl/sitioncmselements that's the repository.
What kind of information do you want to see about the integration?

This is the repo inside RepMan: https://app.repman.io/organization/sition/package/eb778052-4cd4-4b56-86f7-40cd0c4cab2f/details

> And finally, one question: does manual synchronization help and the mentioned version appears in the repman?

No, these are not showing up... 
I have the feeling that nothing is happening in the background.
